### ISSUE TITLE
Preview file in the main buffer

### ISSUE THREAD

**Issue by haze** [bfrg/vim-fzy#4]
I'm opening up another issue to discuss a potential feature (and it's feasibility.)

When I'm using the terminal window at the bottom to select files (for either `FzyGrep` or `FzyFind`, I can only see the line that matches my pattern. It's super helpful to see the surrounding lines (especially for matches that have the same line but are in completely different files)

Is it possible to replace the buffer on top with a preview of the highlighted item in `fly`?

**Comment by bfrg** [comment]
Sadly that's not possible. `fzy` doesn't provide an option to print the currently selected item to a file (or somewhere else) and then keeps printing it out as you cycle through the menu with `CTRL-J` and `CTRL-K`. This would be required in order to implement such a "preview" window.

And I'm not aware of `fzf` to have such an option either. They probably don't need it anyway because they have a builtin preview window. IIRC there was a `dmenu` patch that provided this feature. But it's easier to accomplish in `dmenu` because they can print to `stdout` since the menu itself is drawn as a separate X window. With terminal fuzzy searchers you can't do this because the entire fuzzy menu is written to `stdout` in the terminal, so you would have to write the currently selected item to a file or somewhere else. Then in Vim we would need to "listen" to file changes of that file and act whenever something is written to it.

An alternative is to use a `callback` in `term_start()` and then whenever `fzy` updates its menu, we parse the entire output and search for the cursorline to extract the currently selected filename. That's quite cumbersome and I don't really want to go through this.

**To give you an example:**

If you run `echo one two three four five | cut ' ' '\n' | fzy`, this is what `fzy` prints to `stdout`:
```
 ^[[0m^[[1G> ^[[K^M
 ^[[K^[[7m^[[?7lone^[[?7h^[[0m^M
 ^[[K^[[?7ltwo^[[?7h^[[0m^M
 ^[[K^[[?7lthree^[[?7h^[[0m^M
 ^[[K^[[?7lfour^[[?7h^[[0m^M
 ^[[K^[[?7lfive^[[?7h^[[0m^[[5A^[[1G>
```

In the terminal it looks like this:
![screenshot-2022-11-01_170137](https://user-images.githubusercontent.com/6266600/199282413-edb135b1-3a8b-4c5c-a8f8-2c14119eec22.png)

As you can see the output contains a bunch of terminal escape codes. The first line is the prompt line, and the others are the lines with the items. The second line contains a `^[[7m` which is the selected line. So we would have to extract `one` from that line in order to use it for our preview window.

If you select the next item with `CTRL-J`, the `callback` function in vim would get this:

```
 ^[[1G> ^[[K^M
 ^[[K^[[?7lone^[[?7h^[[0m^M
 ^[[K^[[7m^[[?7ltwo^[[?7h^[[0m^M
 ^[[K^[[?7lthree^[[?7h^[[0m^M
 ^[[K^[[?7lfour^[[?7h^[[0m^M
 ^[[K^[[?7lfive^[[?7h^[[0m^[[5A^[[1G>
```

Screenshot:
![screenshot-2022-11-01_170142](https://user-images.githubusercontent.com/6266600/199282419-2a71c22e-daad-4841-85ee-0a706fdcb546.png)

So now the `^[[7m` has shifted to the third line in the raw output. We would have to first find the line containing the `^[[7m` and then remove all terminal escape codes to obtain the content of the line, in the example above it's the `two`.

But as soon as you insert characters to filter the output, it gets more complicated, for example, if you type `t`, this is what `fzy`  looks like:

![screenshot-2022-11-01_170802](https://user-images.githubusercontent.com/6266600/199282421-5c94b892-f971-4474-a839-0a2bcf54b517.png)

The raw output:
```
 ^[[1G> t^[[K^M
 ^[[K^[[7m^[[?7l^[[33mt^[[39mwo^[[?7h^[[0m^M
 ^[[K^[[?7l^[[33mt^[[39mhree^[[?7h^[[0m^M
 ^[[K^M
 ^[[K^M
 ^[[K^[[5A^[[1G> t
```

As you can see, the `^[[7m` is on the second line but since the line has individual characters highlighted (here it's just a `t`), the raw output looks more complicated. I mean, it is feasible to remove all terminal escape codes to obtain the content of that line, but I really have no motivation to go through all this.

I don't think `fzy` is the right tool for this to begin with. It's a very simple fuzzy searcher. Out of curiosity, why aren't you using `fzf`? I'm actually thinking about switching back to `fzf` because it has some nice features like multi-selection. `fzy` has also some  bugs that do not seem to will get fixed. It looks like the development has stopped some time ago and the author doesn't even answer to the issues or pull requests. 

I'm considering writing my own `fzf` plugin because I find the default `fzf.vim` too bloated, with too many commands that I'll never need.

**Comment by bfrg** [comment]
If you are curious how to obtain the raw output _and_ open `fzy` in a terminal buffer, this is what I did:

```vim
vim9script

term_start([&shell, &shellcmdflag, 'echo one two three four five | tr " " "\n" | fzy'], {
    norestore: true,
    term_finish: 'close',
    term_rows: 11,
    callback: (ch: channel, msg: string) => popup_notification(msg->split('\n'), {
        pos: 'topright',
        col: &columns,
        time: 10000
    })
})
```

The popup windows will close automatically after 10 seconds, or by clicking with the mouse on each one.
